package mso

var targetCosMap = map[string]string{
	"background":            "cos0",
	"best_effort":           "cos1",
	"excellent_effort":      "cos2",
	"critical_applications": "cos3",
	"video":                 "cos4",
	"voice":                 "cos5",
	"internetwork_control":  "cos6",
	"network_control":       "cos7",
	"unspecified":           "unspecified",
	"cos0":                  "background",
	"cos1":                  "best_effort",
	"cos2":                  "excellent_effort",
	"cos3":                  "critical_applications",
	"cos4":                  "video",
	"cos5":                  "voice",
	"cos6":                  "internetwork_control",
	"cos7":                  "network_control",
}

var targetDscpMap = map[string]string{
	"af11":                 "af11",
	"af12":                 "af12",
	"af13":                 "af13",
	"af21":                 "af21",
	"af22":                 "af22",
	"af23":                 "af23",
	"af31":                 "af31",
	"af32":                 "af32",
	"af33":                 "af33",
	"af41":                 "af41",
	"af42":                 "af42",
	"af43":                 "af43",
	"cs0":                  "cs0",
	"cs1":                  "cs1",
	"cs2":                  "cs2",
	"cs3":                  "cs3",
	"cs4":                  "cs4",
	"cs5":                  "cs5",
	"cs6":                  "cs6",
	"cs7":                  "cs7",
	"expedited_forwarding": "expeditedForwarding",
	"voice_admit":          "voiceAdmit",
	"unspecified":          "unspecified",
	"expeditedForwarding":  "expedited_forwarding",
	"voiceAdmit":           "voice_admit",
}
